heat_template_version: 2016-10-14

description: OpenShift cluster

parameters:

outputs:

  etcd_names:
    description: Name of the etcds
    value: { get_attr: [ etcd, name ] }

  etcd_ips:
    description: IPs of the etcds
    value: { get_attr: [ etcd, private_ip ] }

  etcd_floating_ips:
    description: Floating IPs of the etcds
    value: { get_attr: [ etcd, floating_ip ] }

  master_names:
    description: Name of the masters
    value: { get_attr: [ masters, name ] }

  master_ips:
    description: IPs of the masters
    value: { get_attr: [ masters, private_ip ] }

  master_floating_ips:
    description: Floating IPs of the masters
    value: { get_attr: [ masters, floating_ip ] }

  node_names:
    description: Name of the nodes
    value: { get_attr: [ compute_nodes, name ] }

  node_ips:
    description: IPs of the nodes
    value: { get_attr: [ compute_nodes, private_ip ] }

  node_floating_ips:
    description: Floating IPs of the nodes
    value: { get_attr: [ compute_nodes, floating_ip ] }

  infra_names:
    description: Name of the nodes
    value: { get_attr: [ infra_nodes, name ] }

  infra_ips:
    description: IPs of the nodes
    value: { get_attr: [ infra_nodes, private_ip ] }

  infra_floating_ips:
    description: Floating IPs of the nodes
    value: { get_attr: [ infra_nodes, floating_ip ] }

conditions:
  no_floating: false

resources:

  net:
    type: OS::Neutron::Net
    properties:
      name:
        str_replace:
          template: openshift-ansible-cluster_id-net
          params:
            cluster_id: openshift-cluster-heat

  subnet:
    type: OS::Neutron::Subnet
    properties:
      name:
        str_replace:
          template: openshift-ansible-cluster_id-subnet
          params:
            cluster_id: openshift-cluster-heat
      network: { get_resource: net }
      cidr:
        str_replace:
          template: subnet_24_prefix.0/24
          params:
            subnet_24_prefix: 192.168.99
      allocation_pools:
        - start:
            str_replace:
              template: subnet_24_prefix.3
              params:
                subnet_24_prefix: 192.168.99
          end:
            str_replace:
              template: subnet_24_prefix.254
              params:
                subnet_24_prefix: 192.168.99
      dns_nameservers:
        - 8.8.8.8

  router:
    type: OS::Neutron::Router
    properties:
      name:
        str_replace:
          template: openshift-ansible-cluster_id-router
          params:
            cluster_id: openshift-cluster-heat
      external_gateway_info:
        network: ext-net

  interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: subnet }

#  keypair:
#    type: OS::Nova::KeyPair
#    properties:
#      name:
#        str_replace:
#          template: openshift-ansible-cluster_id-keypair
#          params:
#            cluster_id: openshift-cluster-heat
#      public_key: jenkins

  common-secgrp:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          template: openshift-ansible-cluster_id-common-secgrp
          params:
            cluster_id: openshift-cluster-heat
      description:
        str_replace:
          template: Basic ssh/icmp security group for cluster_id OpenShift cluster
          params:
            cluster_id: openshift-cluster-heat
      rules:
        - direction: ingress
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          protocol: icmp
          remote_ip_prefix: 0.0.0.0/0

  master-secgrp:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          template: openshift-ansible-cluster_id-master-secgrp
          params:
            cluster_id: openshift-cluster-heat
      description:
        str_replace:
          template: Security group for cluster_id OpenShift cluster master
          params:
            cluster_id: openshift-cluster-heat
      rules:
        - direction: ingress
          protocol: tcp
          port_range_min: 4001
          port_range_max: 4001
        - direction: ingress
          protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - direction: ingress
          protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - direction: ingress
          protocol: tcp
          port_range_min: 8053
          port_range_max: 8053
        - direction: ingress
          protocol: udp
          port_range_min: 8053
          port_range_max: 8053
        - direction: ingress
          protocol: tcp
          port_range_min: 24224
          port_range_max: 24224
        - direction: ingress
          protocol: udp
          port_range_min: 24224
          port_range_max: 24224
        - direction: ingress
          protocol: tcp
          port_range_min: 2224
          port_range_max: 2224
        - direction: ingress
          protocol: udp
          port_range_min: 5404
          port_range_max: 5405
        - direction: ingress
          protocol: tcp
          port_range_min: 9090
          port_range_max: 9090

  etcd-secgrp:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          template: openshift-ansible-cluster_id-etcd-secgrp
          params:
            cluster_id: openshift-cluster-heat
      description:
        str_replace:
          template: Security group for cluster_id etcd cluster
          params:
            cluster_id: openshift-cluster-heat
      rules:
        - direction: ingress
          protocol: tcp
          port_range_min: 2379
          port_range_max: 2379
          remote_mode: remote_group_id
          remote_group_id: { get_resource: master-secgrp }
        - direction: ingress
          protocol: tcp
          port_range_min: 2380
          port_range_max: 2380
          remote_mode: remote_group_id

  node-secgrp:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          template: openshift-ansible-cluster_id-node-secgrp
          params:
            cluster_id: openshift-cluster-heat
      description:
        str_replace:
          template: Security group for cluster_id OpenShift cluster nodes
          params:
            cluster_id: openshift-cluster-heat
      rules:
        - direction: ingress
          protocol: tcp
          port_range_min: 10250
          port_range_max: 10250
          remote_mode: remote_group_id
        - direction: ingress
          protocol: tcp
          port_range_min: 10255
          port_range_max: 10255
          remote_mode: remote_group_id
        - direction: ingress
          protocol: udp
          port_range_min: 10255
          port_range_max: 10255
          remote_mode: remote_group_id
        - direction: ingress
          protocol: udp
          port_range_min: 4789
          port_range_max: 4789
          remote_mode: remote_group_id
        - direction: ingress
          protocol: tcp
          port_range_min: 30000
          port_range_max: 32767
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          protocol: tcp
          port_range_min: 30000
          port_range_max: 32767
          remote_ip_prefix: "192.168.99.0/24"

  infra-secgrp:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          template: openshift-ansible-cluster_id-infra-secgrp
          params:
            cluster_id: openshift-cluster-heat
      description:
        str_replace:
          template: Security group for cluster_id OpenShift infrastructure cluster nodes
          params:
            cluster_id: openshift-cluster-heat
      rules:
        - direction: ingress
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - direction: ingress
          protocol: tcp
          port_range_min: 443
          port_range_max: 443

  cns-secgrp:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          template: openshift-ansible-cluster_id-cns-secgrp
          params:
            cluster_id: openshift-cluster-heat
      description:
        str_replace:
          template: Security group for cluster_id OpenShift cns cluster nodes
          params:
            cluster_id: openshift-cluster-heat
      rules:
        # glusterfs_sshd
        - direction: ingress
          protocol: tcp
          port_range_min: 2222
          port_range_max: 2222
        # heketi dialing backends
        - direction: ingress
          protocol: tcp
          port_range_min: 10250
          port_range_max: 10250
        # glusterfs_management
        - direction: ingress
          protocol: tcp
          port_range_min: 24007
          port_range_max: 24007
        # glusterfs_rdma
        - direction: ingress
          protocol: tcp
          port_range_min: 24008
          port_range_max: 24008
        # glusterfs_bricks
        - direction: ingress
          protocol: tcp
          port_range_min: 49152
          port_range_max: 49251

  etcd:
    type: OS::Heat::ResourceGroup
    properties:
      count: 3
      resource_def:
        type: server.yaml
        properties:
          name:
            str_replace:
              template: k8s_type-%index%.cluster_id
              params:
                cluster_id: openshift-cluster-heat
                k8s_type: etcd
          cluster_env: builtforcloud.com
          cluster_id:  openshift-cluster-heat
          group:
            str_replace:
              template: k8s_type.cluster_id
              params:
                k8s_type: etcds
                cluster_id: openshift-cluster-heat
          type:        etcd
          image:       Cirros-0.4.0
          flavor:      GENERAL1.Small
          key_name:    jenkins
          net:         { get_resource: net }
          subnet:      { get_resource: subnet }
          net_name:
            str_replace:
              template: openshift-ansible-cluster_id-net
              params:
                cluster_id: openshift-cluster-heat
          secgrp:
            - { get_resource: etcd-secgrp }
            - { get_resource: common-secgrp }
          floating_network:
            if:
              - no_floating
              - ''
              - ext-net
          volume_size: 2
    depends_on:
      - interface

  masters:
    type: OS::Heat::ResourceGroup
    properties:
      count: 3
      resource_def:
        type: server.yaml
        properties:
          name:
            str_replace:
              template: k8s_type-%index%.cluster_id
              params:
                cluster_id: openshift-cluster-heat
                k8s_type: master
          cluster_env: builtforcloud.com
          cluster_id:  openshift-cluster-heat
          group:
            str_replace:
              template: k8s_type.cluster_id
              params:
                k8s_type: masters
                cluster_id: openshift-cluster-heat
          type:        master
          image:       Cirros-0.4.0
          flavor:      GENERAL1.Small
          key_name:    jenkins
          net:         { get_resource: net }
          subnet:      { get_resource: subnet }
          net_name:
            str_replace:
              template: openshift-ansible-cluster_id-net
              params:
                cluster_id: openshift-cluster-heat
          secgrp:
            - { get_resource: master-secgrp }
            - { get_resource: node-secgrp }
            - { get_resource: etcd-secgrp }
            - { get_resource: common-secgrp }
          floating_network:
            if:
              - no_floating
              - ''
              - ext-net
          volume_size: 40
    depends_on:
      - interface

  compute_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: 6
      removal_policies:
      - resource_list: []
      resource_def:
        type: server.yaml
        properties:
          name:
            str_replace:
              template: sub_type_k8s_type-%index%.cluster_id
              params:
                cluster_id: openshift-cluster-heat
                sub_type_k8s_type: app-node
          cluster_env: builtforcloud.com
          cluster_id:  openshift-cluster-heat
          group:
            str_replace:
              template: k8s_type.cluster_id
              params:
                k8s_type: nodes
                cluster_id: openshift-cluster-heat
          type:        node
          subtype:     app
          node_labels:
            region: primary
          image:       Cirros-0.4.0
          flavor:      GENERAL1.Small
          key_name:    jenkins
          net:         { get_resource: net }
          subnet:      { get_resource: subnet }
          net_name:
            str_replace:
              template: openshift-ansible-cluster_id-net
              params:
                cluster_id: openshift-cluster-heat
          secgrp:
            - { get_resource: node-secgrp }
            - { get_resource: common-secgrp }
          floating_network:
            if:
              - no_floating
              - ''
              - ext-net
          volume_size: 40
    depends_on:
      - interface

  infra_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: server.yaml
        properties:
          name:
            str_replace:
              template: sub_type_k8s_type-%index%.cluster_id
              params:
                cluster_id: openshift-cluster-heat
                sub_type_k8s_type: infra-node
          cluster_env: builtforcloud.com
          cluster_id:  openshift-cluster-heat
          group:
            str_replace:
              template: k8s_type.cluster_id
              params:
                k8s_type: infra
                cluster_id: openshift-cluster-heat
          type:        node
          subtype:     infra
          node_labels:
            region: infra
          image:       Cirros-0.4.0
          flavor:      GENERAL1.Small
          key_name:    jenkins
          net:         { get_resource: net }
          subnet:      { get_resource: subnet }
          net_name:
            str_replace:
              template: openshift-ansible-cluster_id-net
              params:
                cluster_id: openshift-cluster-heat
          secgrp:
# TODO(bogdando) filter only required node rules into infra-secgrp
            - { get_resource: node-secgrp }
            - { get_resource: infra-secgrp }
            - { get_resource: common-secgrp }
          floating_network:
            if:
              - no_floating
              - ''
              - ext-net
          volume_size: 40
    depends_on:
      - interface

  cns:
    type: OS::Heat::ResourceGroup
    properties:
      count: 3
      resource_def:
        type: server.yaml
        properties:
          name:
            str_replace:
              template: sub_type_k8s_type-%index%.cluster_id
              params:
                cluster_id: openshift-cluster-heat
                sub_type_k8s_type: cns
          cluster_env: builtforcloud.com
          cluster_id:  openshift-cluster-heat
          group:
            str_replace:
              template: k8s_type.cluster_id
              params:
                k8s_type: cns
                cluster_id: openshift-cluster-heat
          type:        cns
          image:       Cirros-0.4.0
          flavor:      GENERAL1.Small
          key_name:    jenkins
          net:         { get_resource: net }
          subnet:      { get_resource: subnet }
          net_name:
            str_replace:
              template: openshift-ansible-cluster_id-net
              params:
                cluster_id: openshift-cluster-heat
          secgrp:
            - { get_resource: node-secgrp }
            - { get_resource: cns-secgrp }
            - { get_resource: common-secgrp }
          floating_network: ext-net
          volume_size: 40
